-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.aset (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  kode_barang text,
  id_barang text,
  no_register text,
  nama_barang text NOT NULL,
  merk_type text,
  ukuran_cc text,
  bahan text,
  kib text NOT NULL CHECK (kib = ANY (ARRAY['KIB A'::text, 'KIB B'::text, 'KIB C'::text, 'KIB E'::text])),
  tahun_perolehan integer,
  cara_perolehan text,
  sumber_dana text,
  harga bigint DEFAULT 0,
  jumlah integer DEFAULT 1,
  kondisi text DEFAULT 'Baik'::text CHECK (kondisi = ANY (ARRAY['Baik'::text, 'Rusak Ringan'::text, 'Rusak Berat'::text])),
  status_barang text DEFAULT 'Inventaris'::text,
  status_aset text DEFAULT 'Aset Tetap'::text,
  luas_tanah numeric,
  letak_alamat text,
  status_tanah text,
  no_sertifikat text,
  no_pabrik text,
  no_rangka text,
  no_mesin text,
  no_polisi text,
  no_bpkb text,
  tgl_buku date,
  no_bast text,
  tgl_bast date,
  id_penerimaan text,
  lokasi text,
  penggunaan text,
  keterangan text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  kondisi_bangunan text,
  luas_lantai numeric,
  jumlah_lantai integer,
  dokumen_gedung text,
  no_imb text,
  tgl_imb date,
  letak_bangunan text,
  spesifikasi text,
  penerbit text,
  judul_koleksi text,
  satuan text,
  konstruksi_bertingkat text,
  konstruksi_beton text,
  status_tanah_gedung text,
  no_kode_tanah text,
  id_awal_tanah text,
  status_sertifikat_tanah text,
  tahun_cetak integer,
  ukuran_aset text,
  asal_daerah text,
  bahan_aset text,
  jenis_aset text,
  tahun_perolehan_tanah integer,
  no_urut_sertifikat text,
  tgl_sertifikat date,
  penggunaan_tanah text,
  foto_url text,
  dok_spk_url text,
  dok_penawaran_url text,
  dok_baphp_url text,
  dok_bast_url text,
  dok_kuitansi_url text,
  penanggung_jawab_id uuid,
  nama_penanggung_jawab text,
  CONSTRAINT aset_pkey PRIMARY KEY (id),
  CONSTRAINT aset_penanggung_jawab_id_fkey FOREIGN KEY (penanggung_jawab_id) REFERENCES public.penanggung_jawab(id)
);
CREATE TABLE public.dokumen_pengguna (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pengguna_barang_id uuid NOT NULL,
  jenis_dokumen text NOT NULL,
  nama_file text NOT NULL,
  file_path text NOT NULL,
  file_size bigint,
  tgl_upload timestamp without time zone DEFAULT now(),
  CONSTRAINT dokumen_pengguna_pkey PRIMARY KEY (id),
  CONSTRAINT dokumen_pengguna_pengguna_barang_id_fkey FOREIGN KEY (pengguna_barang_id) REFERENCES public.pengguna_barang(id)
);
CREATE TABLE public.pemindahtanganan (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  barang_id uuid NOT NULL,
  dari_pj_id uuid,
  ke_pj_id uuid NOT NULL,
  tanggal date NOT NULL,
  no_dokumen text,
  keterangan text,
  dokumen_url text,
  dibuat_pada timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pemindahtanganan_pkey PRIMARY KEY (id),
  CONSTRAINT pemindahtanganan_barang_id_fkey FOREIGN KEY (barang_id) REFERENCES public.aset(id),
  CONSTRAINT pemindahtanganan_dari_pj_id_fkey FOREIGN KEY (dari_pj_id) REFERENCES public.penanggung_jawab(id),
  CONSTRAINT pemindahtanganan_ke_pj_id_fkey FOREIGN KEY (ke_pj_id) REFERENCES public.penanggung_jawab(id)
);
CREATE TABLE public.peminjaman (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  aset_id uuid,
  nama_peminjam text NOT NULL,
  jabatan text,
  nip text,
  tgl_pinjam date NOT NULL,
  tgl_batas_kembali date NOT NULL,
  tgl_kembali date,
  kondisi_kembali text,
  catatan text,
  catatan_kembali text,
  status text NOT NULL DEFAULT 'dipinjam'::text CHECK (status = ANY (ARRAY['dipinjam'::text, 'dikembalikan'::text])),
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT peminjaman_pkey PRIMARY KEY (id),
  CONSTRAINT peminjaman_aset_id_fkey FOREIGN KEY (aset_id) REFERENCES public.aset(id)
);
CREATE TABLE public.penanggung_jawab (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nama text NOT NULL,
  nip text,
  jabatan text,
  unit_kerja text DEFAULT 'Kecamatan Tenjo'::text,
  no_hp text,
  aktif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT penanggung_jawab_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pengguna_barang (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  aset_id uuid NOT NULL,
  nama_pengguna text NOT NULL,
  nip text NOT NULL,
  jabatan_unit text NOT NULL,
  tgl_mulai_pengguna date NOT NULL,
  tgl_serah_barang date NOT NULL,
  masa_jabatan_akhir date,
  status_pengguna text NOT NULL DEFAULT 'aktif'::text CHECK (status_pengguna = ANY (ARRAY['aktif'::text, 'tidak aktif'::text, 'pensiun'::text])),
  catatan text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT pengguna_barang_pkey PRIMARY KEY (id),
  CONSTRAINT pengguna_barang_aset_id_fkey FOREIGN KEY (aset_id) REFERENCES public.aset(id)
);
CREATE TABLE public.profil_pengguna (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  nama_lengkap text NOT NULL,
  nip text,
  jabatan text,
  unit_kerja text,
  no_hp text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profil_pengguna_pkey PRIMARY KEY (id),
  CONSTRAINT profil_pengguna_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
